### ISSUE TITLE
Player Model

### ISSUE THREAD

**Issue by yeslayla** [sgw-dev/ragdoll-olympics#3]
Details Known: Olympic Competitor

I'm not sure what style we want for this, but as this is for the player entity, this is a high priority task.

I marked this as design as well since it includes determining the art style & character design.

@NuMellow @ecallah3

**Comment by ecallah3** [comment]
[PlayerModel.zip](https://github.com/sgw-dev/ragdoll-olympics/files/5262954/PlayerModel.zip)
Here's my player model, feel free to texture it with simple diffuse colors.

**Comment by yeslayla** [comment]
@oyafusog Hey Greg, can you comment on this issue once you can confirm this model will work for you? Thanks!

**Comment by oyafusog** [comment]
I've added Eric's model with the ragdoll physics added. Please use the RagdollPlayerModel.prefab when throwing the model into a scene. We can texture this guy at a later date.
